language: go
go:
  - master
addons:
  apt:
    packages:
    - xvfb
  ssh_know_hosts: 116.196.84.125

before_install:
  - openssl aes-256-cbc -K $encrypted_b654a88fad19_key -iv $encrypted_b654a88fad19_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa

install:
  - tar -jcvf short-service.tar.bz2 ./
  - scp short-service.tar.bz2 root@116.196.84.125:~/
  - ssh root@116.196.84.125 'mkdir -p short-service && tar -jxvf short-service.tar.bz2 -C short-service && cd short-service'

after_success:
  - make build
  - make run
branches:
  only:
    - master



